name = "dynamics-node"
compatibility_date = "2026-05-08"
compatibility_flags = ["nodejs_compat"]
node_compat = true
main = "./worker.js"

[assets]
directory = "./public"

[build]
command = "npm run build"
